pv_job:
    pattern:  /
    defaults: { _controller: "PvJobeetBundle:Job:index" }

pv_job_show:
    pattern:  /{company}/{location}/{id}/{position}
    defaults: { _controller: "PvJobeetBundle:Job:show" }
    requirements:
        id:   \d+

pv_job_new:
    pattern:  /new
    defaults: { _controller: "PvJobeetBundle:Job:new" }

pv_job_create:
    pattern:  /create
    defaults: { _controller: "PvJobeetBundle:Job:create" }
    requirements: { _method: post }

pv_job_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PvJobeetBundle:Job:edit" }

pv_job_update:
    pattern:  /{id}/update
    defaults: { _controller: "PvJobeetBundle:Job:update" }
    requirements: { _method: post|put }

pv_job_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PvJobeetBundle:Job:delete" }
    requirements: { _method: post|delete }
