parameters:
#    pv_jobeet.example.class: Pv\JobeetBundle\Example

services:
    pv.jobeet.admin.category:
        class:  Pv\JobeetBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Categories }
        arguments: [null, Pv\JobeetBundle\Entity\Category, PvJobeetBundle:CategoryAdmin]

    pv.jobeet.admin.job:
        class:  Pv\JobeetBundle\Admin\JobAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Jobs }
        arguments: [null, Pv\JobeetBundle\Entity\Job, PvJobeetBundle:JobAdmin]